spring.application.name=board

spring.profiles.active=prod

# JPA ?? ??
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# ??? ??
spring.messages.basename=messages

# actuator ??
management.endpoints.web.exposure.include=health,info,prometheus

# prometheus endpoint ???
management.endpoint.prometheus.enabled=true