spring.datasource.url=jdbc:postgresql://localhost:5432/board
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=board
spring.datasource.password=board

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false